=== Reto3Grupo4/Reto3/Documents/Reto3Grupo4/Lenguaje_Marcas/xml/artistas.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="artistas">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="artista" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="nombre" type="xs:string"/>
              <xs:element name="genero" type="xs:string"/>
              <xs:element name="imagen" type="xs:string"/>
              <xs:element name="album">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="titulo" type="xs:string"/>
                    <xs:element name="año" type="xs:date"/>
                    <xs:element name="reproducciones" type="xs:string"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="id" type="xs:int" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Reto3Grupo4/Reto3/Documents/Reto3Grupo4/Lenguaje_Marcas/xml/artistas.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="artistas.xsl"?>
<artistas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="artistas.xsd">
    <artista id="1">
        <nombre>Kaze</nombre>
        <genero>Rap</genero>
        <imagen>img/Kaze.jpg</imagen>
        <album>
            <titulo>Nombre Direccion</titulo>
            <año>2023</año>
            <reproducciones>1.327.701</reproducciones>
        </album>

    </artista>
    <artista id="2">
        <nombre>Bad Bunny</nombre>
        <genero>Reggaeton</genero>
        <imagen>img/bad_bunny.jpg</imagen>
        <album>
            <titulo>Un Verano sin Ti</titulo>
            <año>2022</año>
            <reproducciones>550.459.667</reproducciones>
        </album>
    </artista>
    <artista id="3">
        <nombre>Rosalia</nombre>
        <genero>Flamenco</genero>
        <imagen>img/rosalia.jpg</imagen>
        <album>
            <titulo>El Mal Querer</titulo>
            <año>2018</año>
            <reproducciones>1.000.000.000</reproducciones>
        </album>
    </artista>

=== Reto3Grupo4/Reto3/Lenguaje_Marcas/xml/artistas.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="artistas.xsl"?>
<artistas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="artistas.xsd">
    <artista id="1">
        <nombre>Kaze</nombre>
        <genero>Rap</genero>
        <imagen>img/Kaze.jpg</imagen>
        <album>
            <titulo>Nombre Direccion</titulo>
            <año>2023-08-01</año>
            <reproducciones>1327701</reproducciones>
        </album>
        <album>
            <titulo>Antipop</titulo>
            <año>2021-01-01</año>
            <reproducciones>1327701</reproducciones>
        </album>

    </artista>
    <artista id="2">
        <nombre>Bad Bunny</nombre>
        <genero>Reggaeton</genero>
        <imagen>img/bad_bunny.jpg</imagen>
        <album>
            <titulo>Un Verano sin Ti</titulo>
            <año>2022-07-01</año>
            <reproducciones>550459667</reproducciones>
        </album>
        <album>
            <titulo>Oasis</titulo>
            <año>2019-06-28</año>
            <reproducciones>550459667</reproducciones>
        </album>
    </artista>
    <artista id="3">
        <nombre>Rosalia</nombre>
        <genero>Flamenco</genero>
        <imagen>img/rosalia.jpg</imagen>
        <album>
            <titulo>El Mal Querer</titulo>
            <año>2018-01-01</año>
            <reproducciones>1000000000</reproducciones>
        </album>
        <album>
            <titulo>Motomami</titulo>
            <año>2022-03-18</año>
            <reproducciones>1000000000</reproducciones>
        </album>
    </artista>
</artistas>
