=== Reto3Grupo4/Reto3/Documents/Reto3Grupo4/Lenguaje_Marcas/xml/canciones.xsd
<?xml version="1.0" encoding="UTF-8"?> 
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="canciones">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="cancion" maxOccurs="unbounded">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="titulo" type="xsd:string"/>
                            <xsd:element name="artista" type="xsd:string"/>
                            <xsd:element name="album" type="xsd:string"/>
                            <xsd:element name="genero" type="xsd:string"/>
                            <xsd:element name="duracion" type="xsd:string"/>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== Reto3Grupo4/Reto3/Documents/Reto3Grupo4/Lenguaje_Marcas/xml/canciones.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<?xml-stylesheet type="text/xsl" href="canciones.xsl"?>
<canciones xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="canciones.xsd">
    <cancion>
        <titulo>TKT</titulo>
        <artista>Kaze</artista>
        <album>Nombre Direccion</album>
        <genero>Rap</genero>
        <duracion>3:00</duracion>
    </cancion>
    <cancion>
        <titulo>Tití Me Preguntó</titulo>
        <artista>Bad Bunny</artista>
        <album>Un Verano Sin Ti</album>
        <genero>Reggaeton</genero>
        <duracion>4:03</duracion>
    </cancion>
    <cancion>
        <titulo>Malamente</titulo>
        <artista>Rosalia</artista>
        <album>El Mal Querer</album>
        <genero>Flamenco</genero>
        <duracion>3:28</duracion>
    </cancion>
</canciones>
