=== Reto3Grupo4/Reto3/Documents/Reto3Grupo4/Lenguaje_Marcas/xml/playlist.xsd
<?xml version="1.0" encoding="UTF-8"?> 
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
   <xsd:element name="PlayLists"> 
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="PlayList" maxOccurs="unbounded">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name= "IDPlayList" type="xsd:integer"  minOccurs="1"/>
                            <xsd:element name="titulo" type="xsd:string" minOccurs="1"/>
                            <xsd:element name= "fechaCreacion" type="xsd:date" minOccurs="1"/>
                            <xsd:element name= "IDCliente" type="xsd:integer" minOccurs="1"/>
                        </xsd:sequence>   
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== Reto3Grupo4/Reto3/Documents/Reto3Grupo4/Lenguaje_Marcas/xml/playlist.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="playlist.xsl"?>
<PlayLists xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="playlist.xsd">
    <PlayList>
        <IDPlayList>1</IDPlayList>
<<<<<<< HEAD
        <titulo>Workout Mix</titulo>
        <fechaCreacion>2023-06-20</fechaCreacion>
=======
        <titulo>Rap</titulo>
        <fechaCreacion>2023-05-01</fechaCreacion>
>>>>>>> 3c63749c646b9d122946451728526ce9b61260c3
        <IDCliente>1</IDCliente>
    </PlayList>
    <PlayList>
        <IDPlayList>2</IDPlayList>
<<<<<<< HEAD
        <titulo>Relax Vibes</titulo>
        <fechaCreacion>2024-01-05</fechaCreacion>
=======
        <titulo>Reggaeton</titulo>
        <fechaCreacion>2023-06-01</fechaCreacion>
>>>>>>> 3c63749c646b9d122946451728526ce9b61260c3
        <IDCliente>2</IDCliente>
    </PlayList>
</PlayLists>
