=== Reto3Grupo4/Reto3/Documents/Reto3Grupo4/Lenguaje_Marcas/xml/podcasts.xsd
<?xml version="1.0" encoding="UTF-8"?> 
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="podcasts">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="podcast" maxOccurs="unbounded">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="titulo" type="xsd:string"/>
                            <xsd:element name="podcaster" type="xsd:string"/>
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <xsd:element name="colaboradores" type="xsd:string"/>
                                    </xsd:sequence>
                                </xsd:complexType>
                            <xsd:element name="genero" type="xsd:string"/>
                            <xsd:element name="duracion" type="xsd:string"/>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>

=== Reto3Grupo4/Reto3/Documents/Reto3Grupo4/Lenguaje_Marcas/xml/podcasts.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<podcasts xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="podcasts.xsd">
    <podcast>
    <titulo>Podcast de Musica</titulo>
    <podcaster>Juan Perez</podcaster>
        <colaboradores>Maria Lopez, Carlos Garcia</colaboradores>
    <genero>Musica</genero>
    <duracion>60:00</duracion>
    </podcast>
    <podcast>
    <titulo>Entrevista con Artistas</titulo>
    <podcaster>Maria Lopez</podcaster>
        <colaboradores>Carlos Garcia</colaboradores>
    <genero>Entrevistas</genero>
    <duracion>45:00</duracion>
    </podcast>
</podcasts>
